This example is used to illustrate the **Quantum Metal --> pyPalace** workflow as well as some basic features of pyPalace. Particuarly, we focus on the built-in pyPalace meshing functionality (backend Gmsh) with a working quantum metal example. 

**Note: Quantum Metal (formly known as Qiskit Metal) is NOT a pyPalace dependency.** 
If you want to use this workflow, install Quantum metal separately.

## Build Quantum Metal Design

Below we build a default Quantum Metal TransmonCross with an added rectangle for a Josephson junction lumped port.

In [1]:
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, open_docs
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross
from qiskit_metal.toolbox_python.attr_dict import Dict
from qiskit_metal.qlibrary.core import QComponent

In [2]:
design = designs.DesignPlanar()
gui = MetalGUI(design)

''' add the qubit geometry '''
qubit_options = dict(connection_pads=dict(claw = dict(connector_location = '90', connector_type = '0')))
qubit = TransmonCross(design,'qubit',options=qubit_options)

gui.rebuild() ## need to do this first before the JJ rectangle below will render
 
''' add a rectangular, which we will later define as our Josephson junction lumped port '''
JJ_coordinates = list(design.qgeometry.tables["junction"].geometry.iloc[0].coords)
JJ_y1,JJ_y2 = JJ_coordinates[0][1],JJ_coordinates[1][1]
JJ_y = (JJ_y1 + JJ_y2)/2
JJ_length = abs(JJ_y2-JJ_y1)
JJ_width = float(qubit.options["cross_width"][:-2])*1e-3
port_geometry = draw.rectangle(JJ_width,JJ_length,0,JJ_y)

## add the port to our design ##
design.qgeometry.add_qgeometry("poly",qubit.id,{"josephson_junction": port_geometry},layer=1,subtract=False)

gui.refresh()
gui.autoscale()

### Take a look at our design's polygon qgeometry table 

we will need this to help define what polygons we want to add as attributes to our mesh file. We only want to add surfaces which we will give boundary conditions to later on using pyPalace.

In [3]:
design.qgeometry.tables["poly"]

,component,name,geometry,layer,subtract,helper,chip,fillet
0,1,cross,"POLYGON ((-0.2 -0.01, -0.2 0.01, -0.01 0.01, -...",1,False,False,main,NaN
1,1,cross_etch,"POLYGON ((-0.22 -0.03, -0.22 0.03, -0.03 0.03,...",1,True,False,main,NaN
2,1,claw_connector_arm,"POLYGON ((0.005 0.281, 0.005 0.241, 0.051 0.24...",1,False,False,main,NaN
3,1,claw_connector_etcher,"POLYGON ((0.011 0.287, 0.011 0.247, 0.057 0.24...",1,True,False,main,NaN
4,1,josephson_junction,"POLYGON ((-0.01 -0.22, 0.01 -0.22, 0.01 -0.2, ...",1,False,False,main,NaN

## Mesh the design with pyPalace (Gmsh backend)

In [4]:
from pypalace import mesh

choose which Quantum Metal components we want to give with mesh atrributes IDs to.

For eigenmode modeling of a superconducting qubit, we need:

| Geometry | Boundary Condition |
|---|---|
| `cross` | PEC |
| `claw_connector_arm` | PEC |
| `josephson_junction` | LumpedPort |

We will also need a `far_field` and a `ground_plane` - but these are automatically generated using ```mesh.mesh_Quantum_Metal_design()```. See below.

In [5]:
''' Mesh our Quantum Metal design '''

## define which components we want to give mesh attributes ##
Attributes = {"cross":1,"claw_connector_arm":2,"josephson_junction":3}

mesh_dir = "mesh/"
meshfile = "example00.msh"
path_to_mesh = mesh_dir + meshfile

## mesh the design --> returns pandas.dataframe of labeled mesh attributes ##
## look at readthedocs, mesh_Quantum_Metal_design has a lot of flexibility to control surface mesh size, volume mesh size, substrate size, etc ## 
attributes_table = mesh.mesh_Quantum_Metal_design(design,output_mesh=path_to_mesh,Attributes=Attributes,surface_mesh_size=0.0005);

Info    : Meshing 1D...nts
Info    : [  0%] Meshing curve 49 (Line)
Info    : [ 10%] Meshing curve 50 (Line)
Info    : [ 10%] Meshing curve 51 (Line)
Info    : [ 10%] Meshing curve 52 (Line)
Info    : [ 10%] Meshing curve 53 (Line)
Info    : [ 10%] Meshing curve 54 (Line)
Info    : [ 10%] Meshing curve 55 (Line)
Info    : [ 10%] Meshing curve 56 (Line)
Info    : [ 20%] Meshing curve 57 (Line)
Info    : [ 20%] Meshing curve 58 (Line)
Info    : [ 20%] Meshing curve 59 (Line)
Info    : [ 20%] Meshing curve 60 (Line)
Info    : [ 20%] Meshing curve 61 (Line)
Info    : [ 20%] Meshing curve 62 (Line)
Info    : [ 20%] Meshing curve 63 (Line)
Info    : [ 30%] Meshing curve 64 (Line)
Info    : [ 30%] Meshing curve 65 (Line)
Info    : [ 30%] Meshing curve 66 (Line)
Info    : [ 30%] Meshing curve 67 (Line)
Info    : [ 30%] Meshing curve 68 (Line)
Info    : [ 30%] Meshing curve 69 (Line)
Info    : [ 30%] Meshing curve 70 (Line)
Info    : [ 40%] Meshing curve 71 (Line)
Info    : [ 40%] Meshing curve 72 (Line)
Info    : [ 40%] Meshing curve 73 (Line)
Info    : [ 40%] Meshing curve 74 (Line)
Info    : [ 40%] Meshing curve 75 (Line)
Info    : [ 40%] Meshing curve 76 (Line)
Info    : [ 40%] Meshing curve 77 (Line)
Info    : [ 50%] Meshing curve 78 (Line)
Info    : [ 50%] Meshing curve 79 (Line)
Info    : [ 50%] Meshing curve 80 (Line)
Info    : [ 50%] Meshing curve 81 (Line)
Info    : [ 50%] Meshing curve 82 (Line)
Info    : [ 50%] Meshing curve 83 (Line)
Info    : [ 50%] Meshing curve 84 (Line)
Info    : [ 60%] Meshing curve 85 (Line)
Info    : [ 60%] Meshing curve 86 (Line)
Info    : [ 60%] Meshing curve 87 (Line)
Info    : [ 60%] Meshing curve 88 (Line)
Info    : [ 60%] Meshing curve 89 (Line)
Info    : [ 60%] Meshing curve 90 (Line)
Info    : [ 60%] Meshing curve 91 (Line)
Info    : [ 60%] Meshing curve 92 (Line)
Info    : [ 70%] Meshing curve 93 (Line)
Info    : [ 70%] Meshing curve 94 (Line)
Info    : [ 70%] Meshing curve 95 (Line)
Info    : [ 70%] Meshing curve 96 (Line)
Info    : [ 70%] Meshing curve 97 (Line)
Info    : [ 70%] Meshing curve 98 (Line)
Info    : [ 70%] Meshing curve 99 (Line)
Info    : [ 80%] Meshing curve 100 (Line)
Info    : [ 80%] Meshing curve 101 (Line)
Info    : [ 80%] Meshing curve 102 (Line)
Info    : [ 80%] Meshing curve 103 (Line)
Info    : [ 80%] Meshing curve 104 (Line)
Info    : [ 80%] Meshing curve 105 (Line)
Info    : [ 80%] Meshing curve 106 (Line)
Info    : [ 90%] Meshing curve 107 (Line)
Info    : [ 90%] Meshing curve 108 (Line)
Info    : [ 90%] Meshing curve 109 (Line)
Info    : [ 90%] Meshing curve 110 (Line)
Info    : [ 90%] Meshing curve 111 (Line)
Info    : [ 90%] Meshing curve 112 (Line)
Info    : [ 90%] Meshing curve 113 (Line)
Info    : [100%] Meshing curve 114 (Line)
Info    : [100%] Meshing curve 115 (Line)
Info    : [100%] Meshing curve 116 (Line)
Info    : [100%] Meshing curve 117 (Line)
Info    : [100%] Meshing curve 118 (Line)
Info    : [100%] Meshing curve 119 (Line)
Info    : [100%] Meshing curve 120 (Line)
Info    : Done meshing 1D (Wall 2.61093s, CPU 2.5837s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 13 (Plane, Frontal-Delaunay)
Info    : [ 10%] Meshing surface 15 (Plane, Frontal-Delaunay)
Info    : [ 20%] Meshing surface 17 (Plane, Frontal-Delaunay)
Info    : [ 20%] Meshing surface 18 (Plane, Frontal-Delaunay)
Info    : [ 30%] Meshing surface 19 (Plane, Frontal-Delaunay)
Info    : [ 40%] Meshing surface 20 (Plane, Frontal-Delaunay)
Info    : [ 40%] Meshing surface 21 (Plane, Frontal-Delaunay)
Info    : [ 50%] Meshing surface 22 (Plane, Frontal-Delaunay)
Info    : [ 60%] Meshing surface 23 (Plane, Frontal-Delaunay)
Info    : [ 60%] Meshing surface 24 (Plane, Frontal-Delaunay)
Info    : [ 70%] Meshing surface 25 (Plane, Frontal-Delaunay)
Info    : [ 70%] Meshing surface 26 (Plane, Frontal-Delaunay)
Info    : [ 80%] Meshing surface 27 (Plane, Frontal-Delaunay)
Info    : [ 90%] Meshing surface 28 (Plane, Frontal-Delaunay)
Info    : [ 90%] Meshing surface 29 (Plane, Frontal-Delaunay)
Info    : [100%] Meshing surface 30 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 0.733552s, CPU 0.726803s)
Info    : Meshing 3D...
Info    : 3D Meshing 2 volumes with 1 connected component
Info    : Tetrahedrizing 27445 nodes...
Info    : Done tetrahedrizing 27453 nodes (Wall 1.12223s, CPU 1.10839s)
Info    : Reconstructing mesh...
Info    :  - Creating surface mesh
Info    :  - Identifying boundary edges
Info    :  - Recovering boundary
Info    : Done reconstructing mesh (Wall 3.0148s, CPU 2.95913s)
Info    : Found volume 2
Info    : Found volume 1
Info    : It. 0 - 0 nodes created - worst tet radius 9.93557 (nodes removed 0 0)
Info    : It. 500 - 500 nodes created - worst tet radius 1.67954 (nodes removed 0 0)
Info    : It. 1000 - 1000 nodes created - worst tet radius 1.4749 (nodes removed 0 0)
Info    : It. 1500 - 1500 nodes created - worst tet radius 1.49476 (nodes removed 0 0)
Info    : It. 2000 - 2000 nodes created - worst tet radius 1.35771 (nodes removed 0 0)
Info    : It. 2500 - 2500 nodes created - worst tet radius 1.31709 (nodes removed 0 0)
Info    : It. 3000 - 3000 nodes created - worst tet radius 1.51722 (nodes removed 0 0)
Info    : It. 3500 - 3500 nodes created - worst tet radius 1.26695 (nodes removed 0 0)
Info    : It. 4000 - 4000 nodes created - worst tet radius 1.3146 (nodes removed 0 0)
Info    : It. 4500 - 4500 nodes created - worst tet radius 1.34363 (nodes removed 0 0)
Info    : It. 5000 - 5000 nodes created - worst tet radius 1.13233 (nodes removed 0 0)
Info    : It. 5500 - 5500 nodes created - worst tet radius 1.20789 (nodes removed 0 0)
Info    : It. 6000 - 6000 nodes created - worst tet radius 1.19902 (nodes removed 0 0)
Info    : It. 6500 - 6500 nodes created - worst tet radius 1.05879 (nodes removed 0 0)
Info    : It. 7000 - 7000 nodes created - worst tet radius 1.03492 (nodes removed 0 0)
Info    : It. 7500 - 7500 nodes created - worst tet radius 1.01509 (nodes removed 0 0)
Info    : 3D refinement terminated (35276 nodes total):
Info    :  - 42 Delaunay cavities modified for star shapeness
Info    :  - 0 nodes could not be inserted
Info    :  - 183966 tetrahedra created in 2.88207 sec. (63831 tets/s)
Info    : 1257 node relocations
Info    : Done meshing 3D (Wall 6.91055s, CPU 6.76322s)
Info    : Optimizing mesh...
Info    : Optimizing volume 1
Info    : Optimization starts (volume = 1.08504e+09) with worst = 0.00153457 / average = 0.475324:
Info    : 0.00 < quality < 0.10 :       491 elements
Info    : 0.10 < quality < 0.20 :      5100 elements
Info    : 0.20 < quality < 0.30 :     11391 elements
Info    : 0.30 < quality < 0.40 :     20572 elements
Info    : 0.40 < quality < 0.50 :     20361 elements
Info    : 0.50 < quality < 0.60 :     12174 elements
Info    : 0.60 < quality < 0.70 :      6553 elements
Info    : 0.70 < quality < 0.80 :      6020 elements
Info    : 0.80 < quality < 0.90 :      6061 elements
Info    : 0.90 < quality < 1.00 :      3255 elements
Info    : 3320 edge swaps, 1734 node relocations (volume = 1.08504e+09): worst = 0.0661403 / average = 0.489603 (Wall 0.44109s, CPU 0.437015s)
Info    : 4007 edge swaps, 2388 node relocations (volume = 1.08504e+09): worst = 0.0661403 / average = 0.490406 (Wall 0.858552s, CPU 0.852101s)
Info    : No ill-shaped tets in the mesh :-)
Info    : 0.00 < quality < 0.10 :        51 elements
Info    : 0.10 < quality < 0.20 :      3227 elements
Info    : 0.20 < quality < 0.30 :      8819 elements
Info    : 0.30 < quality < 0.40 :     20350 elements
Info    : 0.40 < quality < 0.50 :     20284 elements
Info    : 0.50 < quality < 0.60 :     12650 elements
Info    : 0.60 < quality < 0.70 :      6904 elements
Info    : 0.70 < quality < 0.80 :      6059 elements
Info    : 0.80 < quality < 0.90 :      6098 elements
Info    : 0.90 < quality < 1.00 :      3247 elements
Info    : Optimizing volume 2
Info    : Optimization starts (volume = 1.08504e+09) with worst = 0.00153457 / average = 0.475041:
Info    : 0.00 < quality < 0.10 :       486 elements
Info    : 0.10 < quality < 0.20 :      5100 elements
Info    : 0.20 < quality < 0.30 :     11416 elements
Info    : 0.30 < quality < 0.40 :     20577 elements
Info    : 0.40 < quality < 0.50 :     20368 elements
Info    : 0.50 < quality < 0.60 :     12202 elements
Info    : 0.60 < quality < 0.70 :      6574 elements
Info    : 0.70 < quality < 0.80 :      6007 elements
Info    : 0.80 < quality < 0.90 :      6036 elements
Info    : 0.90 < quality < 1.00 :      3222 elements
Info    : 3345 edge swaps, 1636 node relocations (volume = 1.08504e+09): worst = 0.0661403 / average = 0.489425 (Wall 0.426583s, CPU 0.422679s)
Info    : 4039 edge swaps, 2303 node relocations (volume = 1.08504e+09): worst = 0.0661403 / average = 0.490273 (Wall 0.827358s, CPU 0.822469s)
Info    : No ill-shaped tets in the mesh :-)
Info    : 0.00 < quality < 0.10 :        49 elements
Info    : 0.10 < quality < 0.20 :      3218 elements
Info    : 0.20 < quality < 0.30 :      8802 elements
Info    : 0.30 < quality < 0.40 :     20361 elements
Info    : 0.40 < quality < 0.50 :     20274 elements
Info    : 0.50 < quality < 0.60 :     12700 elements
Info    : 0.60 < quality < 0.70 :      6910 elements
Info    : 0.70 < quality < 0.80 :      6041 elements
Info    : 0.80 < quality < 0.90 :      6082 elements
Info    : 0.90 < quality < 1.00 :      3223 elements
Info    : Done optimizing mesh (Wall 1.81634s, CPU 1.80103s)
Info    : 35276 nodes 239405 elements
Info    : Writing 'mesh/example00.msh'...
Info    : Done writing 'mesh/example00.msh'

Let's look at the mesh attributes -- we will use these to help us build our pypalace.Config object

In [6]:
attributes_table

                 Name ID     Type
0               cross  1  Surface
1  claw_connector_arm  2  Surface
2  josephson_junction  3  Surface
5           substrate  4   Volume
6                 air  5   Volume
3        ground_plane  6  Surface
4           far_field  7  Surface

## Build and run our Palace simulation

In [7]:
from pypalace import Config, Simulation
from pypalace.builder import Model, Domains, Boundaries, Solver

Define the necessary paths/filenames

In [8]:
''' path to Palace executable ''' 
path_to_palace = "/Users/firasabouzahr/Desktop/AWSPalace/install/bin/palace-arm64.bin" # change to your path

''' choose path & name for Palace configuration file we will build below '''
config_dir = "config/"
path_to_config = config_dir + "example00.json"

#### create Config object, define ["Problem"] block, & define ["Model"] block

In [9]:
my_config = Config(path_to_config)
 
# define config["Problem"]
my_config.add_Problem("Eigenmode",Output="example00_output")

# define config["Model"] block
my_config.add_Model(path_to_mesh,L0=1e-6)

#### Add materials and boundary conditions (["Domains"] & ["Boundaries"] blocks, respectively)

In [10]:
# define materials
silicon = Domains.Material(Attributes = [4],Permeability=1.0,Permittivity=11.45,LossTan=1e-07)
air = Domains.Material([5],1.0,1.0,0.0)
my_materials = [silicon,air] # material list for input into add_Domains()

# define boundary conditions
PECs = Boundaries.PEC([1,2,6,7]) # add perfect electric conductors --> all metal components from Quantum Metal design + ground_plane
JJ = Boundaries.LumpedPort(Index=1,Attributes=[3],Direction="+Y",L=14e-09) # add josephson_junction polygon as inductive lumped port w/ LJ = 14 nH
my_BCs = [PECs,JJ] # boundary condition list for input into add_Boundaries()

# add config["Domains"] and config["Boundaries"] using our material and BC lists above
my_config.add_Domains(my_materials)
my_config.add_Boundaries(my_BCs)

#### Add ["Solver"] 

**Note:** The simulation parameters below are very coarse intentionally such that this simulation can be ran locally. For higher fidelity simulation results, update parameters below to be stricter. See pyPalace [Example 02](https://github.com/FirasAbouzahr/pyPalace/tree/main/Examples/example_01_eigenmode_EPR/example01_script.py) for an exmaple of running on an HPC.

In [11]:
# eigenmode parameters
eigenmode_params = Solver.Eigenmode(Target = 1.0,
                                    Tol = 1.0e-4,
                                    N = 1,
                                    Save = 1)
## linear solver parameters
Linear_params = Solver.Linear(Type="Default",
                              KSPType = "Default",
                              Tol = 1e-4,
                              MaxIts = 25)

## add them to config["Solver"] and solver["Linear"]
my_config.add_Solver(Simulation=eigenmode_params,Order = 1,Linear=Linear_params)

# save it
my_config.save_config(check_validity=True) # checks validity of file and raises error if something is missing

## Create simulation object & run this simulation locally

In [12]:
''' simulate our Quantum Metal design'''

my_sim = Simulation(my_config,path_to_palace) # define simulation object

n=5 # number of MPI ranks
my_sim.run(n=n)

_____________     _______
_____   __   \____ __   /____ ____________
____   /_/  /  __ ` /  /  __ ` /  ___/  _ \
___   _____/  /_/  /  /  /_/  /  /__/  ___/
  /__/     \___,__/__/\___,__/\_____\_____/


--> Warning!
Output folder is not empty; program will overwrite content! (output_test)
Git changeset ID: v0.13.0-509-g360de9ab
Running with 5 MPI processes
Device configuration: cpu
Memory configuration: host-std
libCEED backend: /cpu/self/xsmm/blocked

Added 28 elements in 1 iterations of local bisection for under-resolved interior boundaries
Added 9723 duplicate vertices for interior boundaries in the mesh
Added 24301 duplicate boundary elements for interior boundaries in the mesh
Added 28067 boundary elements for material interfaces to the mesh
Finished partitioning mesh into 5 subdomains

Characteristic length and time scales:
 L₀ = 1.507e-03 m, t₀ = 5.027e-03 ns

Mesh curvature order: 1
Mesh bounding box:
 (Xmin, Ymin, Zmin) = (-7.200e-04, -7.200e-04, -5.000e-04) m
 (Xmax, Ymax, Zmax) = (+7.200e-04, +7.870e-04, +5.000e-04) m

Parallel Mesh Stats:

                minimum     average     maximum       total
 vertices          8636        9001        9648       45006
 edges            48776       49961       51834      249809
 faces            75561       76802       78039      384011
 elements         35439       35841       36193      179207
 neighbors            3           3           4

            minimum     maximum
 h      0.000460701    0.110097
 kappa      1.02823     44.1309

Configuring Robin impedance BC for lumped ports at attributes:
 3: Ls = 2.800e-08 H/sq, n = (-0.0,+0.0,+1.0)

Configuring lumped port circuit properties:
 Index = 1: L = 1.400e-08 H

Configuring Dirichlet PEC BC at attributes:
 1-2, 6-7

Assembling system matrices, number of global unknowns:
 H1 (p = 1): 45006, ND (p = 1): 249809, RT (p = 1): 384011
 Operator assembly level: Partial
 Mesh geometries:
  Tetrahedron: P = 6, Q = 4 (quadrature order = 2)

Configuring SLEPc eigenvalue solver:
 Scaling γ = 2.422e+05, δ = 6.284e-06
 Configuring divergence-free projection
 Using random starting vector
 Shift-and-invert σ = 1.000e+00 GHz (3.158e-02)

Assembling multigrid hierarchy:
 Level 0 (p = 1): 249809 unknowns
 Level 0 (auxiliary) (p = 1): 45006 unknowns

#PETSc Option Table entries:
-eps_monitor # (source: code)
#End of PETSc Option Table entries

 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 1.657276e+02
 1 (restart 0) KSP residual norm 6.995451e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.221e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 1.509069e+03
 1 (restart 0) KSP residual norm 6.397614e-04
GMRES solver converged in 1 iteration (avg. reduction factor: 4.239e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 1.938636e+02
 1 (restart 0) KSP residual norm 6.922155e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 3.571e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 6.284259e+01
 1 (restart 0) KSP residual norm 2.614622e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.161e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 4.599348e+00
 1 (restart 0) KSP residual norm 1.906686e-06
GMRES solver converged in 1 iteration (avg. reduction factor: 4.146e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 2.630651e+01
 1 (restart 0) KSP residual norm 1.054402e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.008e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 7.072900e+01
 1 (restart 0) KSP residual norm 2.945198e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.164e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 1.655843e+01
 1 (restart 0) KSP residual norm 6.996099e-06
GMRES solver converged in 1 iteration (avg. reduction factor: 4.225e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 5.449409e+01
 1 (restart 0) KSP residual norm 2.292457e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.207e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 4.829353e+01
 1 (restart 0) KSP residual norm 2.041106e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.226e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 4.702830e+01
 1 (restart 0) KSP residual norm 1.990079e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.232e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 4.206336e+01
 1 (restart 0) KSP residual norm 1.783205e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.239e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 4.268295e+01
 1 (restart 0) KSP residual norm 1.809167e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.239e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 3.560188e+01
 1 (restart 0) KSP residual norm 1.507352e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.234e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 3.425637e+01
 1 (restart 0) KSP residual norm 1.449778e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.232e-07)
 Residual norms for GMRES solve
 0 (restart 0) KSP residual norm 3.754344e+01
 1 (restart 0) KSP residual norm 1.591375e-05
GMRES solver converged in 1 iteration (avg. reduction factor: 4.239e-07)
  1 EPS nconv=3 first unconverged value (error) 8.07657e-06+1.17413e-10i (1.73158131e-03)

 Linear eigensolve converged (3 eigenpairs) due to CONVERGED_TOL; iterations 1
 Total number of linear systems solved: 16
 Total number of linear solver iterations: 16
 Found 3 converged eigenvalues (first = 1.381e-02+4.465e-10i)

Computing solution error estimates and performing postprocessing

m,        Re{f} (GHz),        Im{f} (GHz),                  Q,      Error (Bkwd.),       Error (Abs.)
1,      +3.720600e+00,      +6.014857e-08,      +3.092842e+07,      +5.371932e-17,      +1.709852e-11
 Wrote mode 1 to disk
2,      +3.920282e+01,      +2.263248e-07,      +8.660743e+07,      +1.604022e-09,      +5.105530e-04
3,      +4.256319e+01,      -7.945296e-07,      +2.678515e+07,      +9.029337e-08,      +2.874001e-02

Completed 0 iterations of adaptive mesh refinement (AMR):
 Indicator norm = 4.525e-01, global unknowns = 249809
 Max. iterations = 0, tol. = 1.000e-02

Elapsed Time Report (s)           Min.        Max.        Avg.
==============================================================
Initialization                   0.096       0.100       0.098
  Mesh Preprocessing             1.858       1.859       1.859
Operator Construction            2.724       2.726       2.725
Linear Solve                     1.044       1.047       1.046
  Setup                          0.524       0.525       0.525
  Preconditioner                 4.535       4.539       4.537
Eigenvalue Solve                 0.823       0.825       0.824
Div.-Free Projection             6.383       6.385       6.384
Estimation                       0.057       0.058       0.058
  Construction                   3.451       3.452       3.452
  Solve                          2.049       2.050       2.050
Postprocessing                   0.498       0.500       0.498
Disk IO                          2.450       2.451       2.451
--------------------------------------------------------------
Total                           26.537      26.537      26.537

## Extract and analyze simulation results

#### Visualize electric field to ensure mode 1 (index=1) is indeed our qubit

In [16]:
%matplotlib inline
my_sim.plot_field(field="E",index=1)

#### Extract transmon qubit frequency and anharmonicity with EPR

For a more in-depth look at EPR analysis see: pyPalace [Example 02 analysis notebook](https://github.com/FirasAbouzahr/pyPalace/tree/main/Examples/example_01_eigenmode_EPR/example01_analysis_notebook.ipynb)

In [14]:
from pypalace.analysis import EPR

f_q = my_sim.get_frequency_eigenmode(mode=1) # qubit frequency
p_q = my_sim.get_portEPR(port_index=1,mode=1) # qubit energy participation ratio to JJ for EPR analysis

alpha = EPR.calculate_anharmonicity(p_q,f_q,LJ=14e-09)

In [15]:
print("Transmon Hamiltonian parameters:")
print("--------------------------------")
print(f"qubit frequency = {f_q:.2f} GHz")
print(f"qubit anharmonicity = {alpha/1e6:.2f} MHz")

Transmon Hamiltonian parameters:
--------------------------------
qubit frequency = 3.72 GHz
qubit anharmonicity = -146.18 MHz